### ISSUE TITLE
demo有问题。

### ISSUE THREAD

**Issue by jincdream** [fex-team/fis3-smarty#10]
$ fis3 release -r common
/usr/local/lib/node_modules/fis3/lib/log.js:201
    throw err
    ^

Error: Load /Users/cjc/dev/common/fis-conf.js error: Cannot find module 'fis3-smarty'
 Error: Cannot find module 'fis3-smarty'

**Comment by jincdream** [comment]
每个项目的 fis-conf.js 应该是 fis.require('smarty')(fis);

开启服务器预览的命令应该为：fis3 server start --type smarty --rewrite

**Comment by oxUnd** [comment]
php-linux 是啥？

**Comment by jincdream** [comment]
![img](http://ww4.sinaimg.cn/bmiddle/68f1197ajw1f0in67504nj204t0670sp.jpg) 一个空的文件夹。不记得哪一步创建出来的了。。

**Comment by jincdream** [comment]
一开始我是照着 readme.md弄的。

**安装本地模拟环境**
- fis3 >= 3.2.6
  
  ``` bash
  # 命令行在 fis3-smarty 的项目目录。
  fis3 server start
  
  # 不在 fis3-smarty 项目目录
  npm install -g fis3-server-smarty
  fis3 server start --type smarty
  ```

**Comment by oxUnd** [comment]
没有会怎么样？

**Comment by jincdream** [comment]
刚删了php-linux试了下，又没问题了。 －。－

**Comment by oxUnd** [comment]
遇到这种问题可能大概是缓存问题，清理一下缓存就可以了。当然按照规则是不会依赖任何文件的（编译）

**Comment by fancyboynet** [comment]
同样遇到了这个问题

```
NGDS:demo ngds$ fis3 release -r common
/usr/local/lib/node_modules/fis3/lib/log.js:201
    throw err
          ^
Error: Load /Users/ngds/work/learning/tool/fis3-smarty/doc/demo/common/fis-conf.js error: Cannot find module 'fis3-smarty' 
 Error: Cannot find module 'fis3-smarty'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ngds/work/learning/tool/fis3-smarty/doc/demo/common/fis-conf.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

 Check this out: https://github.com/fex-team/fis3-errors/issues/2


    at Object.exports.error (/usr/local/lib/node_modules/fis3/lib/log.js:192:11)
    at Object.cli.run (/usr/local/lib/node_modules/fis3/lib/cli.js:206:17)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/fis3/bin/fis.js:31:11)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/fis3/node_modules/liftoff/index.js:185:12)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/fis3/node_modules/liftoff/index.js:153:7)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3


```

**Comment by jincdream** [comment]
@fancyboynet 每个项目的 fis-conf.js 应该是 fis.require('smarty')(fis);

开启服务器预览的命令应该为：fis3 server start --type smarty --rewrite

**Comment by yaoweiprc** [comment]
我也被这个坑了

**Comment by jimmygkr** [comment]
巨坑的玩意

**Comment by whatwg6** [comment]
大家用这个配合vue或者react吗？还是原生写。。。。

**Comment by oxUnd** [comment]
@forzeny 如果是 React 等，还是建议不用后端输出吧。如果是 C 端场景，要求首屏时间，那么可能用这套会比较合适。

**Comment by whatwg6** [comment]
@xiangshouding 奥，都快忘了，这个是需要前端把代码发布到后端开发机的。。。。。

**Comment by oxUnd** [comment]
@forzeny 不是，是后端模板到后端机器上。
