### ISSUE TITLE
无法安装fis3-smarty 

### ISSUE THREAD

**Issue by happy760690** [fex-team/fis3-smarty#18]
$ npm install fis3-smarty
npm WARN package.json fis3-smarty@1.1.14 license should be a valid SPDX license expression
npm WARN install Refusing to install fis3-smarty as a dependency of itself

当执行
$ fis3 release

 [ERROR] Load E:\git_here\fis3-smarty\doc\demo\size\common\fis-conf.js error: Cannot find module 'fis3-smarty'
 Error: Cannot find module 'fis3-smarty'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\git_here\fis3-smarty\doc\demo\size\common\fis-conf.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

 Check this out: https://github.com/fex-team/fis3-errors/issues/2

**Comment by happy760690** [comment]
已经可以运行了
可能是由于网络错误导致的，可以尝试下 fis3 正在测试的新服务。

npm install fis3-command-server -g
npm install fis3-server-smarty -g
然后通过

fis3 server start --type smarty
