### ISSUE TITLE
fis3-smarty 和 fis-plus server冲突？

### ISSUE THREAD

**Issue by wytheme** [fex-team/fis3-smarty#2]
### 1.无法正常显示demo

fis3和fis-plus 均已安装

执行：

```
fis3 server start --type php --rewrite  
```

站点:8080 

```
 “Welcome，我是FIS-PLUS，史上最强大的前端集成解决方案”
```
### 2. fis release  can't find module 'fis-smarty'

```
fis.require('smarty')(fis);
```

大致如此，捣鼓了一会fisp发现此问题已ok，虽已无法重现，还望解答

**Comment by oxUnd** [comment]
命令用错了，你应该用 `fis3`，就这样。

**Comment by wytheme** [comment]
```
➜  common git:(master) ✗ fis3 release

 [ERROR] Load /Users/lwz/Documents/htdocs/h5/site/common/fis-conf.js error: Cannot find module 'fis3-smarty'
 Error: Cannot find module 'fis3-smarty'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lwz/Documents/htdocs/h5/site/common/fis-conf.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

 Check this out: https://github.com/fex-team/fis3-errors/issues/2
```

common/fis-conf.js

```
require('fis3-smarty')(fis);
fis.set('namespace', 'common');
```

能否具体一些，什么命令错了？

**Comment by wytheme** [comment]
明白了  NODE_PATH，绕回来了。
