### ISSUE TITLE
sizeDemo运行错误

### ISSUE THREAD

**Issue by eugeneCN** [fex-team/fis3-smarty#35]
一直用fis来构建我们的项目，之前是java然后我们选择了fis的jello，用的一直挺好。

因业务需求加入php，作为fis的铁杆必然还是选择fis，可按照 https://github.com/fex-team/fis3-smarty/blob/master/doc/README.md 一步一步的安装启动项目总失败。

我通过安装说明按照以下步骤操作的：

首先下载 demo，然后解压，进入这个目录，执行以下命令对所有模块进行构建发布。

```
fis3 release -r common
fis3 release -r subsiteA
fis3 release -r subsiteB
```

然后fis3 server start --type smarty 启动窗口但页面一直显示一个index。

我在url访问common目录 http://127.0.0.1:8080/common

页面报错信息：
```
HTTP ERROR 500

Problem accessing /common. Reason:

    Server Error
Caused by:

java.lang.RuntimeException: PHP Fatal error:  Uncaught exception 'SmartyException' with message 'Unable to load template file '/Users/eMule/.fis3-tmp/www/template/common/index.tpl'' in /Users/eMule/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatebase.php:127
Stack trace:
#0 /Users/eMule/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('/Users/eMule/.f...', NULL, NULL, NULL, true)
#1 /Users/eMule/.fis3-tmp/www/fisdata/TestData.class.php(100): Smarty_Internal_TemplateBase->display('/Users/eMule/.f...')
#2 /Users/eMule/.fis3-tmp/www/index.php(53): TestData::renderHelper(Object(Smarty), '/Users/eMule/.f...')
#3 /Users/eMule/.fis3-tmp/www/index.php(146): fis_debug_render_smarty()
#4 {main}
  thrown in /Users/eMule/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatebase.php on line 127

	at php.java.servlet.fastcgi.FastCGIServlet.parseBody(FastCGIServlet.java:409)
	at php.java.servlet.fastcgi.FastCGIServlet.execute(FastCGIServlet.java:433)
	at php.java.servlet.fastcgi.FastCGIServlet.handle(FastCGIServlet.java:481)
	at php.java.servlet.fastcgi.FastCGIServlet.doGet(FastCGIServlet.java:521)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at com.baidu.fis.HttpServer$FISWebAppContext.doScope(HttpServer.java:138)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Powered by Jetty://

```

困扰好久了，朋友们帮忙看下是什么问题。。 
系统 mac版本 10.11.6
nodejs版本 v4.4.4
fis3版本 v3.4.32
php-cgi版本 PHP 5.5.38 (cgi-fcgi) (built: Mar 31 2017 13:41:14)

**Comment by eugeneCN** [comment]
@BaiduFE @fouber @walterShen @tianlili @BaiduFE 。。。

**Comment by oxUnd** [comment]
url 错了，具体访问的是业务模块下 page 下的某个模板；

http://127.0.0.1:8080/A/page/index
