### ISSUE TITLE
server start报java.lang.NullPointerException

### ISSUE THREAD

**Issue by MinuteWong** [fex-team/fis3-smarty#41]
![Uploading image.png…]()

**Comment by MinuteWong** [comment]
[INFO] Shutdown with pid [7120]
checking php-cgi support : v5.5.38
checking java support : v9.0.1
starting fis-server ... fail
Exception in thread "main" java.lang.NullPointerException
C:\Users\Administrator\AppData\Roaming\npm\node_modules\fis3\lib\log.js:201
    throw err
    ^

Error: fis-server fails to start at port [8080], error: unknown
    at Object.exports.error (C:\Users\Administrator\AppData\Roaming\npm\node_mod                                             ules\fis3\lib\log.js:192:11)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\work\personalCenter\no                                             de_modules\fis3-server-smarty\vendor\server.js:159:15)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by MinuteWong** [comment]
好像不支持Java9，换回Java8就ok了
