### ISSUE TITLE
java.lang.RuntimeException: PHP Fatal error:  Uncaught exception 'SmartyException' with message 'Unable to load template file '

### ISSUE THREAD

**Issue by chilebaby** [fex-team/fis3-smarty#43]
HTTP ERROR 500
Problem accessing /pr/page/index. Reason:

    Server Error
Caused by:
java.lang.RuntimeException: PHP Fatal error:  Uncaught exception 'SmartyCompilerException' with message 'Syntax Error in template &quot;/home/users/zongzhili/.fis3-tmp/www/template/pr/page/layout.tpl&quot;  on line 1 &quot;{%html framework=&amp;quot;pr:static/lib/mod.js&amp;quot;%}&quot; unknown tag &quot;html&quot;' in /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatecompilerbase.php:665
Stack trace:
#0 /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatecompilerbase.php(451): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown tag "ht...', 1)
#1 /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templateparser.php(2388): Smarty_Internal_TemplateCompilerBase->compileTag('html', Array)
#2 /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templateparser.php(3101): Smarty_Internal_Templateparser->yy_r36()
#3 /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templateparser.php(3201): Smarty_Internal_Templateparser->yy_reduce(36 in /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 665

	at php.java.servlet.fastcgi.FastCGIServlet.parseBody(FastCGIServlet.java:409)
	at php.java.servlet.fastcgi.FastCGIServlet.execute(FastCGIServlet.java:433)
	at php.java.servlet.fastcgi.FastCGIServlet.handle(FastCGIServlet.java:481)
	at php.java.servlet.fastcgi.FastCGIServlet.doGet(FastCGIServlet.java:521)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at com.baidu.fis.HttpServer$FISWebAppContext.doScope(HttpServer.java:138)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:619)

**Comment by oxUnd** [comment]
信息已经很清楚了，找不到 tpl，你确认下你的 tpl 是否跟默认规则匹配

**Comment by chilebaby** [comment]
感谢回复。麻烦帮忙看下这行
java.lang.RuntimeException: PHP Fatal error: Uncaught exception 'SmartyCompilerException' with message 'Syntax Error in template "/home/users/zongzhili/.fis3-tmp/www/template/pr/page/layout.tpl" on line 1 "{%html framework=&quot;pr:static/lib/mod.js&quot;%}" unknown tag "html"' in /home/users/zongzhili/.fis3-tmp/www/smarty/sysplugins/smarty_internal_templatecompilerbase.php:665

**Comment by chilebaby** [comment]
是目录下没有plugin的问题

**Comment by oxUnd** [comment]
ok，看差了

**Comment by sunsmeil** [comment]
您好 目录下没有plugin是什么意思 可以详细说下吗
